### ISSUE TITLE
Error on SPM version

### ISSUE THREAD

**Issue by ghost** [spisakt/pTFCE_spm#1]
I every one.

I am very interested with this toolbox and I am familiar with SPM so I install itand try to use it. Unfortunatly their is many error  in the code. I try to solve it by myself but it was a big fail.
My matlab verion is R2013a, with SPM12.

Do you think it is a matlab version problem ?
If it is not, could you give me some advice to solve them ?

Thank you for your time,
Best regards
Rémi J

**Comment by spisakt** [comment]
Dear Remi,

Sorry for the late replay, I overlooked this issue. Did you try the [latest version](https://github.com/spisakt/pTFCE_spm/releases/tag/V0.1.2.1)?
Indeed, the Toolbox has not been exhaustively tested against Matlab versions, so that might be the problem and any feedback is welcome.
What errors do you face?

Cheers,
Tamas
